#cloud-config
hostname: k8s-master-01

users:
  - name: rke2
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGzfTytmafhBngyZ6teDs5/90SERZJj/VfJPtZH19gsO baris.dogu@Bariss-MacBook-Air.local

package_update: true
package_upgrade: true

write_files:
  - path: /etc/motd
    content: |
      Welcome to Kubernetes Master Node

runcmd:
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab