- name: Install RKE2 server
  shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
  args:
    creates: /usr/local/bin/rke2
    
- name: Create RKE2 server config directory
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Create RKE2 server config.yaml with proper TLS SAN settings
  copy:
    dest: /etc/rancher/rke2/config.yaml
    content: |
      tls-san:
        - "{{ ansible_host }}"
        - "{{ inventory_hostname }}"
    mode: '0644'

- name: Enable and start rke2-server service
  systemd:
    name: rke2-server
    enabled: true
    state: started

- name: Wait for RKE2 server to start
  wait_for:
    port: 9345
    host: "{{ ansible_host }}"
    timeout: 120

- name: Copy kubeconfig for later use (raw backup)
  copy:
    remote_src: true
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/{{ ansible_user }}/rke2.yaml
    owner: "{{ ansible_user }}"
    mode: '0600'

- name: Get node token
  slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: node_token

- name: Set fact for node token
  set_fact:
    rke2_node_token: "{{ node_token.content | b64decode | trim }}"

- name: Ensure kubectl symlink exists at /usr/local/bin
  file:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    state: link
    force: true

- name: Ensure .kube directory exists for rke2
  file:
    path: /home/rke2/.kube
    state: directory
    owner: rke2
    mode: '0755'

- name: Read original kubeconfig
  slurp:
    src: /etc/rancher/rke2/rke2.yaml
  register: raw_kubeconfig

- name: Decode and replace 127.0.0.1 with master IP in kubeconfig
  set_fact:
    kubeconfig_content: "{{ raw_kubeconfig.content | b64decode | regex_replace('127\\.0\\.0\\.1', ansible_host) }}"

- name: Write updated kubeconfig to ~/.kube/config
  copy:
    content: "{{ kubeconfig_content }}"
    dest: /home/rke2/.kube/config
    owner: rke2
    mode: '0600'

- name: Show updated kubeconfig IP info
  debug:
    msg: >
      ~/.kube/config has been written using server IP {{ ansible_host }}.
      Try: KUBECONFIG=/home/rke2/.kube/config kubectl get nodes

- name: Show SSH connection information
  debug:
    msg: >
      To connect to this master node via SSH, use:
      ssh -i {{ ansible_ssh_private_key_file | default('~/.ssh/id_ed25519') }} {{ ansible_user }}@{{ ansible_host }}
